const ACTION_TYPES = {
  SCREEN_ACTIVE : 'SCREEN_ACTIVE',
  SCREEN_INACTIVE: 'SCREEN_INACTIVE',
  SET_SCREEN_MESSAGE: 'SET_SCREEN_MESSAGE',
  SET_PASSWORD: 'SET_PASSWORD',
  SAVE_PASSWORD: 'SAVE_PASSWORD',
  SAFE_LOCK: 'SAFE_LOCK',
  SERVICE_MODE: 'SERVICE_MODE',
  READ_SCREEN_MESSAGE: 'READ_SCREEN_MESSAGE'
}

export default ACTION_TYPES;